### ISSUE TITLE
Hitting rate limit for "NicGet"

### ISSUE THREAD

**Issue by lumi017** [kubernetes/cloud-provider-azure#155]
**What happened**:
We have ~150 node cluster running Kubernetes (the hard way). We are using Azure LB managed by Kubernetes controller manager. It works fine when we are only leveraging the public IP LB, but once we create a private IP LB Kubernetes service it creates extra queries for all the NICs of the nodes in the backend pool of the internal loadbalancer (~extra 150). This causes us to hit the rate limit on NicGet. Here is an example of an error message we get from kubernetes when it fails to create the LB: 
```
rate limited(read) for operation:NicGet", ensure(namespace/haproxy-tcp): backendPoolID(/subscriptions/ID/resourceGroups/NAME/providers/Microsoft.Network/loadBalancers/NAME/backendAddressPools/NAME) - failed to ensure host inpool: "azure - cloud provider 
```
The azure.json cloud provider config that we are using with Kubernetes is 
```
  "cloudProviderBackoff": true,
  "cloudProviderBackoffDuration": 6,
  "cloudProviderBackoffExponent": 1.5,
  "cloudProviderBackoffJitter": 1,
  "cloudProviderBackoffRetries": 6,
  "cloudProviderRateLimit": true,
  "cloudProviderRateLimitBucket": 200,
  "cloudProviderRateLimitBucketWrite": 100,
  "cloudProviderRateLimitQPS": 25,
  "cloudProviderRateLimitQPSWrite": 10
```
We have plans to move to 400 nodes support in future, so we need to find a way around this limitation.

**What you expected to happen**: 
Being able to use a private IP and public IP LB without hitting the rate limit

**How to reproduce it**: 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- OS (e.g. from /etc/os-release): CentOS 7.5
- Kernel (e.g. `uname -a`): 3.10.0-862.14.4.el7.x86_64
- Install tools: internal tools
- Others:

**Comment by feiskyer** [comment]
The rate limit is taking effect for all ARM APIs: cloudProviderRateLimitQPS for read and cloudProviderRateLimitQPSWrite for write.

@lumi017  could you set up a bigger cloudProviderRateLimitQPS?

**Comment by djsly** [comment]
@feiskyer what would be your proposed configuration?

**Comment by MarcosMMartinez** [comment]
@feiskyer My questions would be: why are we asking the client (CCM) to set the throttle itself rather than letting the server (ARM) throttle the client (CCM)?

When we check the ARM throttling limits, we see that the throttling limit for 1 ARM instance is 12K reads and 1.2K writes per hour - however, most requests are received by different instances, so the upper limit would be much higher - as the documentation states: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-request-limits

**Comment by feiskyer** [comment]
@djsly I'd suggest setting it with number of nodes. Disable cloudProviderRateLimit is another option.

@MarcosMMartinez `cloudProviderRateLimit` is provided for client side rate limiting, and CCM also honors server side throttling by exponential backoff. `cloudProviderRateLimit` is needed because there're usually other components also interacting with ARM API, hence CCM should ensure it doesn't eat up all the rate limits.
