### ISSUE TITLE
Improve Attach Detach Disk Performance

### ISSUE THREAD

**Issue by sharkymcdongles** [kubernetes/cloud-provider-azure#78]
On my cluster disks can take up to 10 min to attach to my node after a failover because it takes too long to detach from old node before attaching to new one. Is there anything that can be done to fix this performance issue?

**Comment by feiskyer** [comment]
cc @andyzhangx

**Comment by andyzhangx** [comment]
as I know it won't be related, what's your k8s version? @sharkymcdongles recently we fixed an issue which could lead to disk attach/detach failure

**Comment by sharkymcdongles** [comment]
1.13

**Comment by andyzhangx** [comment]
@sharkymcdongles could it repro easily? and on which azure region?

**Comment by andyzhangx** [comment]
This issue could be probably be due to this, the normal attach/detach operation is around 15s.
I will close this issue now, let me know if you have any question, thanks.
**Issue details**:

We found a disk attach/detach issue due to [dirty vm cache PR](https://github.com/kubernetes/kubernetes/pull/58313) introduced from v1.9.2, it would lead to following disk issues:
 - disk attach/detach failure for a long time
 - disk I/O error
 - unexpected disk detachment from VM
 - VM running into failed state due to attaching non-existing disk

> Note: above error may **only** happen when there are multiple disk attach/detach operations in parallel and it's not easy to repro since it happens on a little possibility.


**Related issues**

- [Azure Disks volume attach still times out on Kubernetes 1.10](https://github.com/kubernetes/kubernetes/issues/71344)
- [Azure Disks occasionally mounted in a way leading to I/O errors](https://github.com/kubernetes/kubernetes/issues/71453)

**Fix**

We changed the azure disk attach/detach retry logic in k8s v1.13, switch to use k8s attach-detach controller to do attach/detach disk retry and clean vm cache after every disk operation, this issue is proved to be fixed in our disk attach/detach stress test and also verified in customer env:
- PR [remove retry operation on attach/detach azure disk in azure cloud provider](https://github.com/kubernetes/kubernetes/pull/70568)
- PR [fix azure disk attach/detach failed forever issue](https://github.com/kubernetes/kubernetes/pull/71377)
- PR [fix detach azure disk issue due to dirty cache](https://github.com/kubernetes/kubernetes/pull/71495)


| k8s version | fixed version |
| ---- | ---- |
| v1.9 | issue introduced in v1.9.2, no cherry-pick fix allowed|
| v1.10 | 1.10.12 |
| v1.11 | 1.11.6 |
| v1.12 | 1.12.4 |
| v1.13 | no such issue |

**Work around**:
 - if there is attach disk failure for long time, restart controller manager may work
 - if there is disk not detached for long time, detach that disk manually

**Related issues**
 - [Multi Attach Error](https://github.com/Azure/AKS/issues/477)

/close

**Comment by sharkymcdongles** [comment]
I just restarted a VM from the Azure portal that I cordoned and drained in k8s 1.13. I am still waiting for it to enter stopped status because the detach operations take so long. It took roughly 20 minutes just to enter stopped state. I am now waiting during the updating phase where it detaches the disks. This has taken a further 10 minutes. I don't think this is as fixed as you say it is. Is it possible because this cluster is provisioned with VMs that were created before this fix was made the fix isn't applied there? Or does the fix come from within k8s itself?

**Comment by andyzhangx** [comment]
@sharkymcdongles what's your exact k8s version? The issue I mentioned happens when moving multiple disks from one node to another. That bug I fixed would lead to following issues:
 - disk attach/detach failure for a long time
 - disk I/O error
 - unexpected disk detachment from VM
 - VM running into failed state due to attaching non-existing disk

Back to your issue, if you restart a VM and it needs a long time, it could be simply an azure platform issue, you could provide activity logs and file an azure ticket.

**Comment by dennisameling** [comment]
@andyzhangx It takes around 14 mins in my Kubernetes cluster to attach disks sometimes. Doesn't seem consistent though.
Kubernetes version: 1.12.6 (AKS West Europe)

Got these events:

![image](https://user-images.githubusercontent.com/17739158/54311157-4ab0e100-45d4-11e9-9ce2-7a193a9e8c53.png)

Looking at the events, would you say this is a Kubernetes/AKS issue or an Azure issue?

**Comment by andyzhangx** [comment]
@dennisameling are you attaching multiple disks to one VM in parallel? 14 min is abnormal, we noticed slow disk attachment in west Europe region before, while it recovered finally.
