### ISSUE TITLE
Expanding a node pool with new nodes fails when there is a Public LB associated to some members of the node pools' AS

### ISSUE THREAD

**Issue by djsly** [kubernetes/cloud-provider-azure#88]
Running k8s `v1.11.5`
Following this flow, 

1) we create an AS with 10 VM, they all get an outbound IP defined by the AS outbound IP.
2) we install kubelet, kubelet starts registering to the ARM API using the public IP (outbound IP)
3) Eventually, all nodes are registered in k8s. 
4) A user creates a Service of Type LoadBalancer, the outboundIP if the nodes changes to the frontEnd IP of that LoadBalancer service.
5) We add a new VM to the AS (total count 11 vms), the VM comes up with no outbound IP since it isn't part of the LB's backend pool.
6) Kubelet will fail to communicate with the ARM API preventing the node from ever becoming healthy.

I'm not sure if there could be a way to allow all traffic to the ARM API and other required URI used by Kubelet to not use the Public IP and simply route internally within the Azure Network. like we can do with https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview

**Comment by feiskyer** [comment]
We have agreed that provisioning tools should ensure the outbound connectivity for nodes scaling or upgrading (e.g. by outbound rules for SLB). From cloud provider's view, because the virtual machine hasn't join kubernetes cluster yet, cloud provider couldn't add it to LB backend pools.

Documents are also added in [azure-loadbalancer.md](https://github.com/kubernetes/cloud-provider-azure/blob/master/docs/azure-loadbalancer.md#outbound-connectivity).

/close
